version: '3.8'

services:
  rag-system:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PIP_DEFAULT_TIMEOUT=300
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
